# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='profiles',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
