# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20170901_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='profiles',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
