# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0003_post_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_agent',
        ),
    ]
